// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLHy0p7QHe_ShGVSaYXreOFWTOG0Mt7A4',
    appId: '1:18537326934:web:12da35aeb744782199cef7',
    messagingSenderId: '18537326934',
    projectId: 'debatebox-62809',
    authDomain: 'debatebox-62809.firebaseapp.com',
    storageBucket: 'debatebox-62809.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWs-OoE_mrSNa0xw4t-Rpv8_8XB30QiJc',
    appId: '1:18537326934:android:60a03512f55dea8199cef7',
    messagingSenderId: '18537326934',
    projectId: 'debatebox-62809',
    storageBucket: 'debatebox-62809.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNx1R5LtS7hu6cespnPuqD0mZ4pCjQ-hA',
    appId: '1:18537326934:ios:eb6b3cb2e097744f99cef7',
    messagingSenderId: '18537326934',
    projectId: 'debatebox-62809',
    storageBucket: 'debatebox-62809.appspot.com',
    iosBundleId: 'com.example.debateBox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNx1R5LtS7hu6cespnPuqD0mZ4pCjQ-hA',
    appId: '1:18537326934:ios:e38ddf217aaea25999cef7',
    messagingSenderId: '18537326934',
    projectId: 'debatebox-62809',
    storageBucket: 'debatebox-62809.appspot.com',
    iosBundleId: 'com.example.debateBox.RunnerTests',
  );
}
